# .github/workflows/build-via.yml
name: Build VIA firmware

on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得（サブモジュールはあとで）
      - uses: actions/checkout@v4
        with:
          submodules: false

      # 2) サブモジュールを固定リビジョンで初期化
      - name: Init submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      # 3) ビルド依存ツール + QMK CLI
      - name: Install toolchain & QMK CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git python3 python3-pip \
            gcc-avr avr-libc \
            gcc-arm-none-eabi binutils-arm-none-eabi \
            libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
          python3 -m pip install --user qmk
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # 4) submodule の Python 依存を満たす
      - name: Install QMK Python requirements
        run: |
          python3 -m pip install --user \
            -r src/qmk/qmk_firmware/requirements.txt
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # 5) VIA ファームをビルド
      - name: Compile Corne VIA firmware
        run: |
          make qmk-clean
          kb=crkbd make qmk-init
          kb=crkbd kr=rev4_1/standard km=via make qmk-compile

      # 6) 成果物をアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: corne-via-${{ github.run_number }}
          path: keyboards/crkbd/qmk/qmk_firmware/.build/*.uf2
