name: Build VIA firmware

on: { workflow_dispatch: {} }   # 手動トリガーのみ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得（サブモジュールはここでは取らない）
      - uses: actions/checkout@v4
        with:
          submodules: false

      # 2) サブモジュールを固定リビジョンで初期化
      - name: Init submodules (ignore local changes)
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive   # ← --remote を付けず「固定」だけ

      # 3) AVR toolchain と QMK CLI
      - name: Install toolchain & QMK CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential gcc-avr avr-libc git python3 python3-pip
          python3 -m pip install --user qmk
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # 4) Corne (rev4_1/standard) の VIA ファームをビルド
      - name: Compile Corne VIA firmware
        run: |
          make qmk-clean
          kb=crkbd make qmk-init
          kb=crkbd kr=rev4_1/standard km=via make qmk-compile

      # 5) 生成物をアップロード
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: corne-via-${{ github.run_number }}
          path: keyboards/crkbd/qmk/qmk_firmware/.build/*.hex
